### ISSUE TITLE
"Error getting history. Please try closing and reopening the popup."

### ISSUE THREAD

**Issue by jepace** [EdinUser/YouTubeLocalHistory#7]
Fairly regularly, when I open the extension to see my list, I get a red box that says "Error getting history. Please try closing and reopening the popup." and no videos show up in the list.

**Comment by EdinUser** [comment]
I've made a re-factoring to switch to different storage engine #5 . When new version is deployed in the Extension stores, we can revisit this issue, as of now I don't see in my side :) I think this was solved, but let's test it!

**Comment by jepace** [comment]
I've updated to 2.2, and I still see this error.  I can recreate it by opening the popup when the current tab is not a YouTube tab.  If I switch to a YouTube tab and open the popup, it has the video list.

**Comment by jepace** [comment]
2.4 -- I am not seeing this problem any more!
